// <auto-generated />
using System;
using BudgetApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetApp.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260520021215_AddDebtStartingBalance")]
    partial class AddDebtStartingBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetApp.Api.Data.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Balances", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.FixedCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("PlaidAccountId")
                        .HasColumnType("text")
                        .HasColumnName("plaid_account_id");

                    b.Property<string>("PlaidMerchantName")
                        .HasColumnType("text")
                        .HasColumnName("plaid_merchant_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UserHasApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("user_has_approved");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FixedCosts", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.PaycheckSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DebtPaymentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_payment_amount");

                    b.Property<decimal>("FixedCostsUntilNextPaycheck")
                        .HasColumnType("numeric")
                        .HasColumnName("fixed_costs_until_next_paycheck");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dismissed");

                    b.Property<decimal>("LeftoverAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("leftover_amount");

                    b.Property<decimal>("NewDynamicBudgetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("new_dynamic_budget_amount");

                    b.Property<DateTime>("NextPaycheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_paycheck_date");

                    b.Property<decimal>("OverBudgetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("over_budget_amount");

                    b.Property<decimal>("PaycheckAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("paycheck_amount");

                    b.Property<DateTime>("PaycheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paycheck_date");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_date");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_date");

                    b.Property<decimal>("PriorPeriodRemaining")
                        .HasColumnType("numeric")
                        .HasColumnName("prior_period_remaining");

                    b.Property<decimal>("PriorPeriodSpend")
                        .HasColumnType("numeric")
                        .HasColumnName("prior_period_spend");

                    b.Property<decimal?>("PriorPeriodStartingBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("prior_period_starting_budget");

                    b.Property<decimal?>("RecommendedDebtPaymentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("recommended_debt_payment_amount");

                    b.Property<decimal>("SavingsContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("savings_contribution");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserDecision")
                        .HasColumnType("text")
                        .HasColumnName("user_decision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasUnderBudget")
                        .HasColumnType("boolean")
                        .HasColumnName("was_under_budget");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PaycheckDate")
                        .IsUnique();

                    b.ToTable("PaycheckSummaries", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.PlaidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Cursor")
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<string>("InstitutionLogo")
                        .HasColumnType("text")
                        .HasColumnName("institution_logo");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text")
                        .HasColumnName("institution_name");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemIds");

                    b.Property<DateTime?>("NotificationsEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notifications_enabled_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlaidItems", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal?>("BudgetAppliedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("budget_applied_amount");

                    b.Property<bool>("CountedAsIncome")
                        .HasColumnType("boolean")
                        .HasColumnName("counted_as_income");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal?>("HoldOverrideAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("hold_override_amount");

                    b.Property<bool>("HoldReviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("hold_reviewed");

                    b.Property<bool>("IsLargeExpenseCandidate")
                        .HasColumnType("boolean")
                        .HasColumnName("IsLargeExpenseCandidate");

                    b.Property<bool>("IsSuspiciousHold")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspicious_hold");

                    b.Property<bool>("LargeExpenseHandled")
                        .HasColumnType("boolean")
                        .HasColumnName("LargeExpenseHandled");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Pending")
                        .HasColumnType("boolean")
                        .HasColumnName("pending");

                    b.Property<string>("PlaidTransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plaid_transaction_id");

                    b.Property<int>("SuggestedKind")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_kind");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserDecision")
                        .HasColumnType("integer")
                        .HasColumnName("user_decision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Transactions_UserId_PlaidTransactionId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<decimal?>("DebtPerPaycheck")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_per_paycheck");

                    b.Property<decimal?>("DebtStartingBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_starting_balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<decimal>("ExpectedPaycheckAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_paycheck_amount");

                    b.Property<string>("FirebaseUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firebase_uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_complete");

                    b.Property<int>("PayDay1")
                        .HasColumnType("integer")
                        .HasColumnName("pay_day_1");

                    b.Property<int>("PayDay2")
                        .HasColumnType("integer")
                        .HasColumnName("pay_day_2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Api.Data.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expo_push_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.Balance", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany("Balances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.FixedCost", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany("FixedCosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.PaycheckSummary", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.PlaidItem", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany("PlaidItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.Transaction", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.UserDevice", b =>
                {
                    b.HasOne("BudgetApp.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetApp.Api.Data.User", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("FixedCosts");

                    b.Navigation("PlaidItems");
                });
#pragma warning restore 612, 618
        }
    }
}
